### ISSUE TITLE
Fix Memory Leak #1 XGetVisualInfo

### ISSUE THREAD

**Issue by LukasKalbertodt** [LukasKalbertodt/lumina#12]
A memory leak (allocated in some X function). Not my fault, but fix anyways ^_^

**Comment by LukasKalbertodt** [comment]
```
==7797==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2560 byte(s) in 1 object(s) allocated from:
    #0 0x4b549e in realloc (/home/lukas/dev/gitlumina/colorTriangle.bin+0x4b549e)
    #1 0x7f7be3d7a9ba in XGetVisualInfo (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x3b9ba)

SUMMARY: AddressSanitizer: 2560 byte(s) leaked in 1 allocation(s).
```

**Comment by LukasKalbertodt** [comment]
Nevermind: It's optirun/primusrun fault. Need to get latest drivers...

**Comment by LukasKalbertodt** [comment]
Nevermind^2: Without optirun/primusrun leaks still occur:

```
==11724==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 104 byte(s) in 1 object(s) allocated from:
    #0 0x4b132b (/home/lukas/dev/lumina-sandbox/test.bin+0x4b132b)
    #1 0x7ffa86acea11 (/usr/lib/x86_64-linux-gnu/mesa/libGL.so.1+0x45a11)

Direct leak of 10 byte(s) in 2 object(s) allocated from:
    #0 0x49c72d (/home/lukas/dev/lumina-sandbox/test.bin+0x49c72d)
    #1 0x7ffa7e243c87 (/usr/lib/x86_64-linux-gnu/dri/i965_dri.so+0x220c87)

SUMMARY: AddressSanitizer: 114 byte(s) leaked in 3 allocation(s).
```

EDIT: Looks like a driver bug. Further investigation needed.
